sonar.organization=xhrobj
sonar.projectKey=xhrobj_gophprofile

# Проект анализируется из GitHub Actions.
# В SonarQube Cloud должен быть отключен Automatic Analysis:
# Administration -> Analysis Method -> Automatic Analysis

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=\
cmd/**/main.go,\
**/*_test.go

sonar.exclusions=\
bin/**

# CPD-исключения оставлены здесь для видимости как намерение.
# Фактически они были настроены в UI SonarCloud:
# Project -> Administration -> General settings -> Analysis Scope
sonar.cpd.exclusions=\
  **/*_test.go
