apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: server
  namespace: gophprofile
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/instance: monitoring-kube-prometheus-prometheus
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: minio
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: rabbitmq
      ports:
        - protocol: TCP
          port: 5672
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: worker
  namespace: gophprofile
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: worker
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/instance: monitoring-kube-prometheus-prometheus
      ports:
        - protocol: TCP
          port: 9092
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: minio
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: rabbitmq
      ports:
        - protocol: TCP
          port: 5672
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: migrate
  namespace: gophprofile
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: migrate
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres
  namespace: gophprofile
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: worker
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: migrate
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio
  namespace: gophprofile
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: minio
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: worker
      ports:
        - protocol: TCP
          port: 9000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq
  namespace: gophprofile
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gophprofile
              app.kubernetes.io/component: worker
      ports:
        - protocol: TCP
          port: 5672
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/instance: monitoring-kube-prometheus-prometheus
      ports:
        - protocol: TCP
          port: 15692
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: gophprofile
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: gophprofile
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
