apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gophprofile-rabbitmq
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: rabbitmq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: rabbitmq
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
    - port: prometheus
      path: /metrics/detailed
      params:
        family:
          - queue_coarse_metrics
      interval: 15s
      scrapeTimeout: 10s
