apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: rabbitmq
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: prometheus
      port: 15692
      targetPort: prometheus
