{{- if .Values.postgres.auth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" (list . "postgres") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "postgres.auth.password is required when postgres.auth.create=true" .Values.postgres.auth.password | quote }}
{{- end }}
{{- if .Values.minio.auth.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" (list . "minio") | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ required "minio.auth.rootUser is required when minio.auth.create=true" .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ required "minio.auth.rootPassword is required when minio.auth.create=true" .Values.minio.auth.rootPassword | quote }}
{{- end }}
{{- if .Values.rabbitmq.auth.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" (list . "rabbitmq") | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ required "rabbitmq.auth.username is required when rabbitmq.auth.create=true" .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ required "rabbitmq.auth.password is required when rabbitmq.auth.create=true" .Values.rabbitmq.auth.password | quote }}
{{- end }}
