{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" (list . "application") | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: {{ required "secrets.databaseDsn is required when secrets.create=true" .Values.secrets.databaseDsn | quote }}
  S3_ACCESS_KEY: {{ required "secrets.s3AccessKey is required when secrets.create=true" .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ required "secrets.s3SecretKey is required when secrets.create=true" .Values.secrets.s3SecretKey | quote }}
  RABBITMQ_URL: {{ required "secrets.rabbitmqUrl is required when secrets.create=true" .Values.secrets.rabbitmqUrl | quote }}
{{- end }}
