apiVersion: v1
kind: ServiceAccount
metadata:
  name: gophprofile-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" (list . "application") | nindent 4 }}
automountServiceAccountToken: false
