apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" (list . "server") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gophprofile.selectorLabels" (list . "server") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
