apiVersion: v1
kind: ServiceAccount
metadata:
  name: gophprofile-app
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: application
automountServiceAccountToken: false
